require("katve.katpack").add({
	"gh:danymat/neogen",
	"gh:williamboman/mason.nvim",
	"gh:brenoprata10/nvim-highlight-colors",
	"gh:stevearc/conform.nvim",
	"gh:mfussenegger/nvim-lint",
	"gh:nvim-mini/mini.icons",
	"gh:HiPhish/rainbow-delimiters.nvim",
	"gh:b0o/incline.nvim",
	"gh:lambdalisue/suda.vim",
	"gh:mfussenegger/nvim-dap",
	"gh:OXY2DEV/markview.nvim",
	"gh:lewis6991/gitsigns.nvim",
	"gh:nvim-telescope/telescope.nvim",
	"gh:folke/trouble.nvim",
	"gh:folke/which-key.nvim",
	"gh:echasnovski/mini.bracketed",
	"gh:echasnovski/mini.files",
	"gh:chentoast/marks.nvim",
	"gh:chrisgrieser/nvim-rip-substitute",
	"gh:nvim-mini/mini.surround",
	"gh:folke/flash.nvim",
	"gh:mbbill/undotree",
	"gh:numToStr/Comment.nvim",
	"gh:nvim-mini/mini.ai",
	"gh:EdenEast/nightfox.nvim",
	"gh:yorickpeterse/nvim-tree-pairs",
	"gh:aserowy/tmux.nvim",
	"gh:danymat/neogen",
	"gh:williamboman/mason.nvim",
	"gh:atiladefreitas/dooing",
	"gh:NeogitOrg/neogit",

	{ src = "gh:ptdewey/pendulum-nvim",                    branch = "v2",                                                                             build = ":PendulumRebuild", },
	{ src = "gh:vyfor/cord.nvim",                          build = ":Cord update", },
	{ src = "gh:nvim-treesitter/nvim-treesitter",          build = ":TSUpdate", },
	{ src = "gh:esmuellert/codediff.nvim",                 dependencies = { "gh:MunifTanjim/nui.nvim" } },
	{ src = "gh:SmiteshP/nvim-navic",                      dependencies = { "gh:neovim/nvim-lspconfig" } },
	{ src = "gh:nanozuki/tabby.nvim",                      dependencies = { "gh:nvim-tree/nvim-web-devicons" } },
	{ src = "gh:jedrzejboczar/possession.nvim",            dependencies = { "gh:nvim-lua/plenary.nvim" }, },
	{ src = "gh:nvim-lualine/lualine.nvim",                dependencies = { "gh:nvim-tree/nvim-web-devicons" }, },
	{ src = "gh:ibhagwan/fzf-lua",                         dependencies = { "gh:nvim-mini/mini.icons" } },
	{ src = "gh:neovim/nvim-lspconfig",                    dependencies = { "gh:saghen/blink.cmp" }, },
	{ src = "gh:ckolkey/ts-node-action",                   dependencies = { "gh:nvim-treesitter/nvim-treesitter" }, },
	{ src = "gh:anuvyklack/animation.nvim",                dependencies = { "gh:anuvyklack/middleclass" }, },
	{ src = "gh:folke/noice.nvim",                         dependencies = { "gh:ibhagwan/fzf-lua", "gh:MunifTanjim/nui.nvim" }, },
	{ src = "gh:anuvyklack/windows.nvim",                  dependencies = { "gh:anuvyklack/middleclass", "gh:anuvyklack/animation.nvim" }, },
	{ src = "gh:lukas-reineke/indent-blankline.nvim",      dependencies = { "gh:HiPhish/rainbow-delimiters.nvim", "gh:shellRaining/hlchunk.nvim", }, },
	{ src = "gh:rachartier/tiny-code-action.nvim",         dependencies = { "gh:nvim-lua/plenary.nvim", "gh:nvim-telescope/telescope.nvim" },         opts = {}, },
	{ src = "gh:theprimeagen/harpoon",                     dependencies = { "gh:nvim-lua/plenary.nvim", branch = "harpoon2" } },
	{ src = "gh:nvim-telescope/telescope-fzy-native.nvim", dependencies = { { src = "gh:romgrk/fzy-lua-native", build = "make", } }, },
	{ src = "gh:stevearc/aerial.nvim",                     dependencies = { "gh:nvim-treesitter/nvim-treesitter", "gh:nvim-tree/nvim-web-devicons" }, },
	{ src = "gh:L3MON4D3/LuaSnip",                         dependencies = { "gh:rafamadriz/friendly-snippets" },                                      build = "make install_jsregexp", },
	{ src = "gh:Saghen/blink.cmp",                         dependencies = { "gh:rafamadriz/friendly-snippets", },                                     version = vim.version.range("v1.*"), build = "cargo build --release", },
})

require("tree-pairs")
require("tmux")
require("neogen")
require("mason")
require("dooing")
require("neogit")
